// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: {
    // Memberikan fallback URL jika DATABASE_URL tidak diset di file .env
    url: env('DATABASE_URL') || 'file:./prisma',
  },
});